version: 5.0.0.{build}
environment:
    PROJECT_NAME: 'Cube.Forms'
clone_folder: 'C:\Cube\%PROJECT_NAME%'
image: Visual Studio 2019
platform: Any CPU
configuration: Release
skip_tags: true
branches:
    only:
        - master
nuget:
    project_feed: true
    disable_publish_on_pr: true
before_build:
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget restore "%PROJECT_NAME%.sln"
build:
    project: '%PROJECT_NAME%.sln'
    parallel: true
    publish_nuget: true
    verbosity: minimal
